import type { NextPage } from 'next';
import Head from 'next/head';
import styles from './Main.module.css';

const Main: NextPage = () => {
  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />
      <Timer controls={}/>
    </div>
  );
};

export default Main;
