import type { NextPage } from 'next';
import Head from 'next/head';
import { Page } from 'components/page/page';
import styles from './main.module.css';

const Index: NextPage = () => {
  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page />
    </div>
  );
};

export default Index;
